### ISSUE TITLE
Compatibility of go compiler's error message prompt

### ISSUE THREAD

**Issue by xushiwei** [qiniu/goplus#325]
To forbid surprise, we should be aware of compatibility of go compiler's error message prompt.

**Comment by visualfc** [comment]
写了一个模仿 Golang 编译信息的测试。 Go+ 的 cl 目前使用  log.Panicln ，可以在之前加入 yyerror 记录语法错误信息，修改 log.Panicln 为 logpanicln 调用 panic 完成（log.Panicln 会引起 stdout 顺序问题)。
这样根据需要可以同时显示源码语法错误和定位 cl 堆栈位置。

yyerror  记录编译语法错误信息 ( 需要按 Golang 编译信息添加在 logpanicln 前，目前有 log.Panicln 120 个左右）
logpanicln 记录 panic 堆栈信息,(PanicMode 控制) 代替目前的 log.Panicln

- Golang compile report error

```
func main() {
 a := "hello"
 println(a, b+c)
}
```
compile error
```
# github.com/goplus/gop/cmd/qfile/temp
.\main.go:5:13: undefined: b
.\main.go:5:15: undefined: c
```
https://github.com/golang/go/blob/master/src/cmd/compile/internal/gc/subr.go
yyerror for report build source error postion and detail

- Go+ simulate Golang yyerror for mini test code

https://github.com/visualfc/goplus/blob/dumperror/cl/compile.go

https://github.com/visualfc/goplus/blob/dumperror/cl/expr.go: L112
```
 } else if mode == lhsAssign || err != syscall.ENOENT {
  yyerror(ctx, ident, "undefined: %v", name)
  logpanicln("compileIdentLHS failed:", err, "-", name)
 } else {
```
yyerror : report Go+ compile error soruce postion and detail
logpanicln: panic and report Go+ compile cl source panic info.  Trace by PanicMode

PanicMode = TracePanic
```
main.gop:3:11: undefined: b
panic: compileIdent failed: unknown - b


goroutine 1 [running]:
github.com/goplus/gop/cl.logpanicln(0xc00006b9d0, 0x2, 0x2)
 E:/DEV/goplus/cl/compile.go:230 +0x9e
github.com/goplus/gop/cl.compileIdent(0xc00005b680, 0xc0000048a0, 0x20)
 E:/DEV/goplus/cl/expr.go:214 +0x1002
。。。
```

PanicMode = ExitOnPanic
```
main.gop:3:11: undefined: b
```

PanicMode = ExitOnSkip
```
main.gop:3:11: undefined: b
main.gop:3:13: undefined: c
panic: don't call me

goroutine 1 [running]:
github.com/goplus/gop/cl.(*funcResults).Kind(0xc0000885b0, 0x1)
 E:/DEV/goplus/cl/value.go:124 +0x40
github.com/goplus/gop/cl.binaryOpResult(0x1, 0x6d0660, 0xc0000885b0, 0x6d0700, 0xc0000885c0, 0x1, 0x6a7380, 0xc0000bdba0)
 E:/DEV/goplus/cl/expr.go:588 +0xe5
github.com/goplus/gop/cl.compileBinaryExpr(0xc0000ab680, 0xc0000ab440, 0x5814d5)
 E:/DEV/goplus/cl/expr.go:572 +0x169
。。。
```
